config/routes.rb
Rails.application.routes.draw do



  resources :posts do 
    resources :comments
  end

  resources :comments do 
    resources :comments
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :users, only: [:show, :index]

  get 'home/index'
  get '/search_users', to: 'search#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, optional: true
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord

	has_many :posts
	has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_commentable

  def index
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.create(content: params[:comment][:content], user_id: current_user.id)
    redirect_to post_path(params[:comment][:whichpost])
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :whichpost)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post
    else
      flash[:notice] = "Post save was unsuccessful. Make sure both title and content have some content."
    end
  end

  def edit
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def update
  end

  def destroy
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	respond_to do |format|
  		@results = User.where('first_name LIKE ?', "%#{params[:name]}%")
  		format.js
  	end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  	@posts = User.find(params[:id]).posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li class="comment">
	<p>
		<h6><%= link_to User.find(comment.user_id).username, user_path(User.find(comment.user_id)) %></h6>
		<%= comment.content %></br>
	</p>
	<p><small>
		<%= time_ago_in_words(comment.created_at) %> ago
	</small></p>

	<% if user_signed_in? %>
		<%= render "comments/form", comment: comment %>
	<% end %>

	<ul>
		<%= render comment.comments %>
	</ul>
</li>

app/views/comments/_form.html.erb
<%= form_for [comment, Comment.new] do |f| %>
	<div class="form-group">
		<%= f.text_area :content, class: "form-control", rows: "2", placeholder: "Comment..." %>
		<%= f.hidden_field :whichpost, value: @post.id %>
	</div>
	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$('#comments').reload();

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/home/index.html.erb
<h1>Welcome to BlogEase</h1>
<p>This is a simple blogging application I made to show my proficiency with Ruby on Rails. I'm using Devise for user login functionality, Bootstrap for styling, and a polymorphic association on the comment model so that you can comment on comments. Feel free to make an account to try out making a post or commenting.</p>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<% if user_signed_in? %>
	<%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
<% else %>
	<p class="alert alert-secondary" >Please Sign In to make a post</p>
<% end %>

<h2>BlogEase's Every Post</h2>

<% @posts.each do |post| %>
	<h3>
		<%= link_to post.title, post %>
	</h3>
	<p>
		<%= link_to User.find(post.user_id).username, user_path(User.find(post.user_id)) %><small> • <%= time_ago_in_words(post.created_at) %> ago</small>
		</p>
<% end %>

app/views/posts/new.html.erb
<% if user_signed_in? %>
	<%= form_with model: @post do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>	
		</div>
		<div class="form-group">
			<%= f.label :content %>
			<%= f.text_area :content, class: "form-control", rows: "5" %>	
		</div>
		<%= f.submit "Submit" %>
	<% end %>
<% else %>
	<div class="alert alert-info">
		You must be signed in to write a post.
	</div>
<% end %>

app/views/posts/show.html.erb
<% if !user_signed_in? %>
	<div class="alert alert-primary" role="alert">
		You must be logged in to comment.
	</div>
<% end %>

<!-- post -->
	<h3>
		<%= @post.title %>
	</h3>

	<p>
		<%= @post.content %>
	</p>

	<p><small>
		<%= time_ago_in_words(@post.created_at) %> ago
	</small></p>

<div id="comments">
	<!-- post comment form -->
	<% if user_signed_in? %>
		<%= form_for [@post, Comment.new], local: true do |f| %>
			<div class="form-group">
				<%= f.text_area :content, class: "form-control", rows: "3", placeholder: "Comment..." %>
				<%= f.hidden_field :whichpost, value: @post.id %>
			</div>
			<%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	<% end %>

	<!-- comments -->
		<ul>
			<%= render partial: 'comments/comment', collection: @post.comments %>
		</ul>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h2><%= User.find(params[:id]).username %>'s Every Post</h2>

<% @posts.each do |post| %>
	<h3>
		<%= link_to post.title, post %>
	</h3>
	<p>
		<%= link_to User.find(post.user_id).username, user_path(User.find(post.user_id)) %><small> • <%= time_ago_in_words(post.created_at) %> ago</small>
		</p>
<% end %>